// upexport.ts — the export record, schema v2 (report §7 phase 2). Owns: the
// ONE DTO a committed package is described by, its builder, and the serializer.
// The record IS the commit: it is written last, inside the generation it
// describes, and the package's single commit pointer names that generation.
//
// Identity, not a filename: rootName + pairId + the source's CONTENT SHA-256
// (R02) + the metadata policy version. Provenance is generation-time: the
// prompt, the provider/model, the request id and the reported usage are stored
// with the answer they produced, never re-read from today's configuration.
// Deployment media (the JPEG's final embedded bytes) is what the output records
// describe (R08) — the writer hashes the artifact the commit pass will write.
//
// Reading (strict validation, tolerant fallback, donor classification) lives in
// upexportread.ts so this file stays the shape's single owner.

import { sanitizeExportSettings, type ExportSettings } from "./upsettings";
import type { IconMetadata } from "./upmeta";

/** The record's schema identity — a version number alone is not one (R24). */
export const EXPORT_SCHEMA = "iconsplitter.upload.package";
export const EXPORT_RECORD_VERSION = 2;

export interface OptimizerRecord {
  version: string;
  config: string;
  beforeBytes: number;
  afterBytes: number;
}

/** An output file that exists in the committed generation. */
export interface OutputRecord {
  /** Path from the picked root, e.g. `<pair>/export/generations/<gen>/<base>.svg`. */
  relPath: string;
  bytes: number;
  sha256: string;
}

export interface SvgOutputRecord extends OutputRecord {
  optimizer: OptimizerRecord | null;
}

export interface JpegOutputRecord extends OutputRecord {
  width: number;
  height: number;
  /** The honest megapixel count of the actual dimensions. */
  mpx: number;
  quality: number;
}

export type EpsOutputRecord = OutputRecord;

/** Where the accepted metadata came from, at the moment it was produced. */
export interface MetadataProvenance {
  /** "user" = typed/accepted by hand; "ai" = generated by the provider. */
  origin: "user" | "ai";
  prompt: string;
  model: string;
  /** Hostname only — never a key, never a query (RULE 20). */
  endpointHost: string;
  requestId: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  /** Always labelled an estimate in the UI; the API reports tokens, not money. */
  estimatedCostUsd: number | null;
  generatedAt: string;
  /** Which policy version accepted this metadata. */
  policy: string;
}

export interface ExportRecord {
  schema: typeof EXPORT_SCHEMA;
  v: typeof EXPORT_RECORD_VERSION;
  pairId: string;
  /** The pair's base name (the AI stem without `_AI`) — every output shares it. */
  iconBase: string;
  /** The picked root's identity at capture/scan time (never a bare name). */
  rootName: string;
  /** The pair folder, relative to the root. */
  dirPath: string;
  source: { relPath: string; version: number; sha256: string; bytes: number };
  settings: ExportSettings;
  metadata: IconMetadata;
  provenance: MetadataProvenance;
  /** What the export was asked to produce; `eps` is the optional one. */
  requested: { svg: true; jpeg: true; eps: boolean };
  outputs: { svg: SvgOutputRecord; jpeg: JpegOutputRecord; eps: EpsOutputRecord | null };
  /** The generation directory this record describes. */
  generation: string;
  /** processed = every requested output committed; partial names the failure. */
  state: "processed" | "partial";
  failure: string | null;
  committedAt: string;
}

export interface BuildRecordArgs {
  pairId: string;
  iconBase: string;
  rootName: string;
  dirPath: string;
  source: ExportRecord["source"];
  settings: ExportSettings;
  metadata: IconMetadata;
  provenance: MetadataProvenance;
  requested: ExportRecord["requested"];
  outputs: ExportRecord["outputs"];
  generation: string;
  state: ExportRecord["state"];
  failure: string | null;
  committedAt: string;
}

export function buildExportRecord(a: BuildRecordArgs): ExportRecord {
  return {
    schema: EXPORT_SCHEMA,
    v: EXPORT_RECORD_VERSION,
    pairId: a.pairId,
    iconBase: a.iconBase,
    rootName: a.rootName,
    dirPath: a.dirPath,
    source: a.source,
    settings: sanitizeExportSettings(a.settings),
    metadata: a.metadata,
    provenance: a.provenance,
    requested: a.requested,
    outputs: a.outputs,
    generation: a.generation,
    state: a.state,
    failure: a.state === "partial" ? a.failure : null,
    committedAt: a.committedAt,
  };
}

export function serializeExportRecord(r: ExportRecord): string {
  return JSON.stringify(r);
}

/** The pointer file: the ONLY thing a commit replaces (R01). */
export interface PackagePointer {
  schema: typeof EXPORT_SCHEMA;
  v: typeof EXPORT_RECORD_VERSION;
  generation: string;
  record: ExportRecord;
}

export function serializePointer(r: ExportRecord): string {
  const pointer: PackagePointer = { schema: EXPORT_SCHEMA, v: EXPORT_RECORD_VERSION, generation: r.generation, record: r };
  return JSON.stringify(pointer);
}

/**
 * A generation id that is stable for one commit and safe as a directory name:
 * the ISO timestamp with ':' and '.' replaced, plus a disambiguating suffix
 * when a generation with that name already exists.
 */
export function generationId(now: string, taken: readonly string[]): string {
  const base = `gen-${now.replace(/[:.]/g, "-")}`;
  if (!taken.includes(base)) return base;
  for (let n = 2; ; n += 1) {
    const candidate = `${base}-${n}`;
    if (!taken.includes(candidate)) return candidate;
  }
}
