// RULE 8 — the clean export boundary runs on real parsed SVG: it makes the
// root SVG 1.1 with a valid viewBox, strips names/editor bloat, and refuses
// raster content or references that cannot survive removal of object IDs.
import { describe, expect, it } from "vitest";
import { cleanExportSvg } from "../src/lib/upload/svgclean";
import { embedMetadataInSvg, readEmbeddedMetadata } from "../src/lib/upload/embed";
import type { IconMetadata } from "../src/lib/upload/meta";

const NS = `xmlns="http://www.w3.org/2000/svg"`;
const SOURCE = `<svg ${NS} xmlns:i="http://ns.adobe.com/AdobeIllustrator/10.0/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" version="1.0" width="24" height="16" viewBox="0 0 24 16" preserveAspectRatio="none" i:foo="bar" inkscape:version="1.2">
  <!-- generated by an editor -->
  <sodipodi:namedview id="namedview1"/>
  <title>Editor source title</title><desc>Editor source description</desc>
  <g id="layer1" class="object" inkscape:groupmode="layer" inkscape:label="Named layer" data-name="user object" aria-label="User object">
    <path id="path1" d="M1 1h22v14H1z" fill="#123456"/>
  </g>
</svg>`;

function docOf(svg: string): Document {
  return new DOMParser().parseFromString(svg, "image/svg+xml");
}

const META: IconMetadata = {
  title: "Minimal line icon of growth",
  description: "Clean line icon showing growth and rising business trends",
  tags: ["icon", "pictogram", "vector", "stroke", "line", "editable", "web", "growth", "speed", "chart"],
};

describe("cleanExportSvg", () => {
  it("sets SVG 1.1, preserves a valid viewBox and removes IDs, names and editor bloat", () => {
    const output = cleanExportSvg(SOURCE);
    const doc = docOf(output);
    const root = doc.documentElement;
    expect(doc.querySelector("parsererror")).toBeNull();
    expect(root.getAttribute("version")).toBe("1.1");
    expect(root.getAttribute("viewBox")).toBe("0 0 24 16");
    expect(root.getAttribute("xmlns")).toBe("http://www.w3.org/2000/svg");
    expect(root.getAttribute("xmlns:xlink")).toBe("http://www.w3.org/1999/xlink");
    expect(root.getAttribute("xml:space")).toBe("preserve");
    expect(root.getAttribute("preserveAspectRatio")).toBe("xMidYMid meet");
    expect(doc.querySelectorAll("[id], [class], [name], [data-name], [data-icon], [inkscape\\:label]")).toHaveLength(0);
    expect(doc.querySelector("metadata, title, desc, namedview")).toBeNull();
    expect(output).not.toContain("xmlns:i=");
    expect(output).not.toContain("xmlns:inkscape=");
    expect(output).not.toContain("xmlns:sodipodi=");
    expect(output).not.toContain("generated by an editor");
    expect(doc.getElementsByTagName("path").length).toBe(1);
    expect(doc.getElementsByTagName("path")[0].getAttribute("fill")).toBe("#123456");
  });

  it("rebuilds a missing viewBox from valid SVG pixel dimensions", () => {
    const svg = `<svg ${NS} width="640px" height="480px"><path d="M0 0h24v12z"/></svg>`;
    expect(docOf(cleanExportSvg(svg)).documentElement.getAttribute("viewBox")).toBe("0 0 640 480");
  });

  it("rejects malformed XML, a non-SVG root, and missing or invalid viewBox", () => {
    expect(() => cleanExportSvg(`<svg><path></svg>`)).toThrow(/well-formed XML/i);
    expect(() => cleanExportSvg(`<html ${NS} viewBox="0 0 1 1"/>`)).toThrow(/root is not <svg>/i);
    expect(() => cleanExportSvg(`<svg ${NS}><path d="M0 0h1v1z"/></svg>`)).toThrow(/viewBox/i);
    expect(() => cleanExportSvg(`<svg ${NS} viewBox="0 0 -2 20"><path d="M0 0h1v1z"/></svg>`)).toThrow(/viewBox/i);
  });

  it("rejects raster image elements and embedded PNG or JPEG data", () => {
    expect(() => cleanExportSvg(`<svg ${NS} viewBox="0 0 24 24"><image href="data:image/png;base64,AAAA" width="24" height="24"/></svg>`))
      .toThrow(/raster|image/i);
    expect(() => cleanExportSvg(`<svg ${NS} viewBox="0 0 24 24"><path d="M0 0h1v1z" fill="url(data:image/jpeg;base64,AAAA)"/></svg>`))
      .toThrow(/raster|image/i);
    expect(() => cleanExportSvg(`<svg ${NS} viewBox="0 0 24 24"><style>.x{fill:url(data:image/png;base64,AAAA)}</style><path class="x" d="M0 0h1v1z"/></svg>`))
      .toThrow(/raster|image/i);
  });

  it("fails closed when an SVG paint or href reference needs an ID", () => {
    const gradient = `<svg ${NS} viewBox="0 0 24 24"><defs><linearGradient id="g"><stop offset="0" stop-color="#000"/></linearGradient></defs><path d="M0 0h24v24z" fill="url(#g)"/></svg>`;
    const use = `<svg ${NS} viewBox="0 0 24 24"><path id="shape" d="M0 0h24v24z"/><use href="#shape"/></svg>`;
    const cssId = `<svg ${NS} viewBox="0 0 24 24"><style>#shape{fill:#000}</style><path id="shape" d="M0 0h24v24z"/></svg>`;
    const cssClass = `<svg ${NS} viewBox="0 0 24 24"><style>.shape{fill:#000}</style><path class="shape" d="M0 0h24v24z"/></svg>`;
    expect(() => cleanExportSvg(gradient)).toThrow(/reference|ID/i);
    expect(() => cleanExportSvg(use)).toThrow(/reference|ID/i);
    expect(() => cleanExportSvg(cssId)).toThrow(/CSS selector/i);
    expect(() => cleanExportSvg(cssClass)).toThrow(/CSS selector/i);
  });

  it("embeds generated metadata after source naming/editor metadata is removed", () => {
    const svg = embedMetadataInSvg(cleanExportSvg(SOURCE), META);
    const doc = docOf(svg);
    expect(readEmbeddedMetadata(svg)).toEqual(META);
    expect(doc.querySelectorAll("[id], [class], [inkscape\\:label], [sodipodi\\:namedview]")).toHaveLength(0);
    expect(doc.documentElement.getAttribute("version")).toBe("1.1");
    expect(doc.documentElement.getAttribute("viewBox")).toBe("0 0 24 16");
  });
});
